---
abstract: 'XS bridge to fast C fibonacci heap implementation'
author:
  - 'Sergey Aleynikov <sergey.aleynikov@gmail.com>'
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Heap-Fibonacci-Fast
no_index:
  directory:
    - inc
    - t
requires:
  XSLoader: 0
  perl: 5.5.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.0101
